export const orgaosExpedidores = [
  { value: "SSP", label: "SSP - Secretaria de Segurança Pública" },
  { value: "DETRAN", label: "DETRAN - Departamento de Trânsito" },
  { value: "PF", label: "PF - Polícia Federal" },
  { value: "CNT", label: "CNT - Carteira Nacional de Habilitação" },
  { value: "DIC", label: "DIC - Diretoria de Identificação Civil" },
  { value: "CTPS", label: "CTPS - Carteira de Trabalho e Previdência Social" },
  { value: "FGTS", label: "FGTS - Fundo de Garantia do Tempo de Serviço" },
  { value: "IFP", label: "IFP - Instituto Félix Pacheco" },
  { value: "IPF", label: "IPF - Instituto Pereira Faustino" },
  { value: "IML", label: "IML - Instituto Médico-Legal" },
  { value: "MTE", label: "MTE - Ministério do Trabalho e Emprego" },
  { value: "MEX", label: "MEX - Ministério do Exército" },
  { value: "MAE", label: "MAE - Ministério da Aeronáutica" },
  { value: "MMA", label: "MMA - Ministério da Marinha" },
  { value: "POF", label: "POF - Polícia Federal" },
  { value: "POM", label: "POM - Polícia Militar" },
  { value: "SES", label: "SES - Secretaria de Estado da Segurança" },
  { value: "SJS", label: "SJS - Secretaria da Justiça e Segurança" },
  {
    value: "SJTS",
    label: "SJTS - Secretaria da Justiça do Trabalho e Segurança",
  },
];
